# Generated by Django 6.0.2 on 2026-02-17 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='icon',
            field=models.CharField(blank=True, help_text='Nome do ícone', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('monument', 'Monumento'), ('restaurant', 'Restaurante'), ('interest', 'Ponto de Interesse'), ('beach', 'Praia'), ('supermarket', 'Supermercado')], max_length=20),
        ),
    ]
