# Generated by Django 6.0.2 on 2026-05-30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_options_place_created_at_place_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='places/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='thumbnail'),
        ),
    ]
