# Generated by Django 6.0.2 on 2026-05-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['order', 'name'], 'verbose_name': 'local', 'verbose_name_plural': 'Locais'},
        ),
    ]
