# Generated by Django 6.0.2 on 2026-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='link da página'),
        ),
    ]
