# Generated by Django 6.0.2 on 2026-02-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_description_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
