# Generated by Django 6.0.2 on 2026-06-01 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_number_alter_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICalSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('feed_url', models.URLField(verbose_name='link iCal')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='última sincronização')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='quarto')),
            ],
            options={
                'verbose_name': 'sincronização iCal',
                'verbose_name_plural': 'sincronizações iCal',
                'ordering': ('room', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_uid', models.CharField(max_length=255, verbose_name='referência iCal')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='título')),
                ('guest_name', models.CharField(blank=True, max_length=200, verbose_name='nome do hóspede')),
                ('check_in', models.DateField(verbose_name='entrada')),
                ('check_out', models.DateField(verbose_name='saída')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('unknown', 'Desconhecida')], default='confirmed', max_length=20, verbose_name='estado')),
                ('raw_summary', models.CharField(blank=True, max_length=255, verbose_name='resumo original')),
                ('raw_description', models.TextField(blank=True, verbose_name='descrição original')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='vista na última sincronização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='quarto')),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.icalsync', verbose_name='sincronização')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ('check_in', 'room'),
                'unique_together': {('sync', 'external_uid')},
            },
        ),
    ]
