# Generated by Django 6.0.2 on 2026-06-01 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_guest_address_guest_email_guest_name_guest_phone'),
        ('rooms', '0004_icalsync_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.guest', verbose_name='hóspede criado'),
        ),
    ]
