# Generated by Django 6.0.2 on 2026-05-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_breakfastrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('starter', 'Entrada'), ('main', 'Prato principal'), ('dessert', 'Sobremesa'), ('drink', 'Bebida'), ('other', 'Outro')], default='main', max_length=20, verbose_name='categoria')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='preço')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponível')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'item da ementa',
                'verbose_name_plural': 'ementa',
                'ordering': ('category', 'order', 'name'),
            },
        ),
    ]
