# Generated by Django 6.0.2 on 2026-05-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Nova'), ('preparing', 'Em preparação'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], default='new', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.guest')),
            ],
            options={
                'verbose_name': 'encomenda',
                'verbose_name_plural': 'encomendas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MenuOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='preço unitário')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.menuitem', verbose_name='prato')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.menuorder')),
            ],
            options={
                'verbose_name': 'item da encomenda',
                'verbose_name_plural': 'itens da encomenda',
            },
        ),
    ]
