# Generated by Django 6.0.2 on 2026-05-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_menuitem_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('guest', 'Hóspede'), ('staff', 'Equipa')], max_length=10, verbose_name='remetente')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.guest')),
            ],
            options={
                'verbose_name': 'mensagem de chat',
                'verbose_name_plural': 'chat',
                'ordering': ('created_at',),
            },
        ),
    ]
